[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "casparcg-scanner"
dynamic = ["version"]
description = "CasparCG Media Scanner"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask",
    "lxml",
    "waitress",
    "watchdog"
]

[project.scripts]
casparcg-scanner = "casparcg_scanner.__main__:main"

[tool.setuptools]
packages = ["casparcg_scanner"]

[tool.setuptools.dynamic]
version = {attr = "casparcg_scanner.__version__"}
