name: Create Release

on:
  push:
    tags:
      - 'debian/*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - env:
          FULL_NAME: ${{ github.repository }}
          FULL_TAG: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NAME="${FULL_NAME#*/}"
          VERS="${FULL_TAG#debian/}"
          VERS="${VERS#*[0-9]%}"
          gh release create "$FULL_TAG" --title "$NAME $VERS" --generate-notes

  build_wheel:
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
          cache: "pip"
      - run: |
          python3 -m pip install --upgrade pip
          pip install build
          python3 -m build
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.ref_name }}" dist/*.whl

  build_binary:
    needs: create_release
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: casparcg-scanner-linux-amd64
          - os: ubuntu-22.04-arm
            asset_name: casparcg-scanner-linux-arm64
          - os: windows-latest
            asset_name: casparcg-scanner-windows-amd64.exe
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install . pyinstaller
          pyinstaller --onefile casparcg-scanner
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv dist/casparcg-scanner* "dist/${{ matrix.asset_name }}"
          gh release upload "${{ github.ref_name }}" "dist/${{ matrix.asset_name }}"
